[tool.poetry]
name = "poc poetry"
version = "0.1.0"
description = "POC"
authors = ["Alfredo"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pytest = "7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
